### ISSUE TITLE
Not an issue, just a question on why it doesn't specifically work on the Python Edition calcs

### ISSUE THREAD

**Issue by Anderson-Cooper** [beckadamtheinventor/BOS#4]
Title.

**Comment by beckadamtheinventor** [comment]
The bootcode cryptographically verifies the OS every time the calc boots. The only reason it works at all on older calculators is either on really old calculators where there wasn't any boot-time verification, or prior to revision M calculators for which a bootcode patch could be actually applied. The revision M (and newer) calculators have a different flash chip which can't be written to unless you wanna go through the effort of desoddering and resoddering the chip.

Apologies that it took me so long to reply.
